### PR TITLE
Action retries

### LINKED ISSUE #484: Implement automatic action retries
- automatically retry failed actions, where those actions are idempotent (non operations)
- add a 'idempotentActionRetries' setting to ProjectConfig, defaulted to 3 (?), which determines the number of retries

### LINKED ISSUE #485: Change action failure error messages
Include a warehouse specific prefix in errors thrown by dbadapter.execute.

e.g. "BigQuery error: ..."

### PR DESCRIPTION
**Pull request by GJMcGowan**
Fixes #484
Fixes #485

### CODE REVIEW

File: api/utils/retry_promise.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+type RetryReturnType = (func: () => Promise<any>, retries: number, error?: Error) => Promise<any>;
+
+export const retryPromise: RetryReturnType = async (func, retries, error) => {
```
Comment (BenBirt) [inline api/utils/retry_promise.ts]:
```suggestion
export async function retryPromise (func: () => Promise<any>, retries: number, error?: Error) => {
```

File: api/utils/retry_promise.ts [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+  if (retries < 0) {
```
Comment (BenBirt) [inline api/utils/retry_promise.ts]: i think this would be cleaner if we put it inside the `catch` block, and check for when `retries === 0`. that way, you don't need to pass the `Error` down the recursion stack.

File: api/utils/retry_promise.ts [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+    throw error;
+  }
+
+  try {
+    const funcResult = await func();
+    return funcResult;
```
Comment (BenBirt) [inline api/utils/retry_promise.ts]:
```suggestion
    return await func();
```

File: api/utils/retry_promise.ts (hunk 1 above)
Comment (BenBirt) [inline api/utils/retry_promise.ts]: can we just call this function, and file, `retry`?

File: api/commands/run.ts [hunk 4]
```diff
@@ -247,10 +248,15 @@ export class Runner {
...
-        maxResults: 1
-      });
+      // Retry this function a given number of times, configurable by user
+      const rows = await retryPromise(
+        () =>
+          this.adapter.execute(task.statement, {
+            onCancel: handleCancel => this.eEmitter.on(CANCEL_EVENT, handleCancel),
+            maxResults: 1
+          }),
+        this.graph.projectConfig.idempotentActionRetries || 0
```
Comment (BenBirt) [inline api/commands/run.ts]: we should *always* have zero retries for any non-idempotent action, i.e. any task of type "operations"

(longer term we will want to let the user mark their actions as idempotent or not, but for now we can assume that operations aren't, everything else is.)

File: api/commands/run.ts [hunk 5]
```diff
@@ -264,7 +270,9 @@ export class Runner {
       taskResult.status = this.cancelled
         ? dataform.TaskResult.ExecutionStatus.CANCELLED
         : dataform.TaskResult.ExecutionStatus.FAILED;
-      taskResult.errorMessage = e.message;
+      const warehouse = this.graph.projectConfig.warehouse;
+      const capitalisedWarehouse = `${warehouse.charAt(0).toUpperCase()}${warehouse.slice(1)}`;
```
Comment (BenBirt) [inline api/commands/run.ts]: let's not bother, this will end up being super weird for e.g. "Bigquery" and "Sqldatawarehouse". i'm fine with just lowercasing it, but if you prefer then feel free to add a user visible name mapping along the lines of the stuff we have near `WarehouseType`

File: protos/core.proto [hunk 6]
```diff
@@ -12,6 +12,7 @@ message ProjectConfig {
   string assertion_schema = 5;
 
   string schema_suffix = 7;
+  int32 idempotent_action_retries = 8;
```
Comment (BenBirt) [inline protos/core.proto]: nit: let's put it above `schema_suffix` which folks aren't really supposed to set in `dataform.json`.

File: api/commands/run.ts (hunk 4 above)
Comment (BenBirt) [inline api/commands/run.ts]: what about a default value of `3`?

File: api/utils/retry_promise.ts (hunk 1 above)
Comment (GJMcGowan) [reply api/utils/retry_promise.ts]: Had to do a manual type, but I implemented the spirit of your suggestion:

```
export async function retryPromise(
  func: () => Promise<any>,
  retries: number,
  error?: Error
): Promise<any> {
```

File: api/commands/run.ts (hunk 4 above)
Comment (GJMcGowan) [reply api/commands/run.ts]: Scary, done

Comment (GJMcGowan) [reply api/commands/run.ts]: Seems like it could make runs a lot slower to fail if a ton of stuff is failing though

Comment (GJMcGowan) [reply api/commands/run.ts]: Changed line to this:

```
task.type === "operation" ? 0 : this.graph.projectConfig.idempotentActionRetries || 3
```

So operations will never retry.
