### PR TITLE
Changes warehouse state calculation to throw an error instead of swallowing it

### LINKED ISSUE #495: Errors not handled during state computation can lead to unexpected behaviour
When we attempt to compute state in the warehouse, and get information about a table / view at run startup, we silently catch errors and treat it as meaning the table does not exist.

This is not OK, because the table fetch request may fail for other reasons, such as flakiness. This can lead to failed runs, as the wrong built SQL will be generated.

### PR DESCRIPTION
**Pull request by GJMcGowan**
Fixes #495

### CODE REVIEW

File: api/commands/state.ts [hunk 1]
```diff
@@ -1,23 +1,18 @@
...
 import { dataform } from "@dataform/protos";
 
-export function state(
+export async function state(
   compiledGraph: dataform.ICompiledGraph,
   dbadapter: IDbAdapter
 ): Promise<dataform.IWarehouseState> {
-  const tables: dataform.ITableMetadata[] = [];
+  const allTables = await Promise.all(
+    compiledGraph.tables
```
Comment (BenBirt) [inline api/commands/state.ts]:
```suggestion
    compiledGraph.tables
      .map(async t => dbadapter.table(t.target))
      // Skip tables that don't exist.
      .filter(async table => !!(await table).type)
```
