### PR TITLE
Fix #1805: failing dry-runs when table/view/assertion do not exist

### LINKED ISSUE #1805: Dry run fails when table/view/assertion to be created does not exists
There are two possible errors relating to dry run: 
#### Tables / views
1. If the table created by a .sqlx file is not already materialised on BigQuery the dry run will fail due to dry run trying to `setMetadata` on an view/table that does not exist yet. Relevant lines of code
 
https://github.com/dataform-co/dataform/blob/54dfa9ce51b141124608f0b5e15fa01f714e093a/cli/api/commands/run.ts#L371

https://github.com/dataform-co/dataform/blob/54dfa9ce51b141124608f0b5e15fa01f714e093a/cli/api/dbadapters/bigquery.ts#L235-L239

In these lines metadata for the table/view that already does not exist will be undefined and trying to access `.schema` attribute of undefined results in the error shown below
 
CleanShot 2024-08-12 at 19 16 41@2x

-----

#### Assertion 

Assertion dry run will face if the table it is trying to create does not already exists. Possibly due to trying to run the following query in the current code base which tries to select from a object that does not exist yet

https://github.com/dataform-co/dataform/blob/54dfa9ce51b141124608f0b5e15fa01f714e093a/cli/api/dbadapters/execution_sql.ts#L177

----- 

#### Minimal example to reproduce

1. Add the following as a new .sqlx file to a dataform project 
```sql
config {
  type: "table",
  schema: "dataset_name",
  description: "any non empty description",
  tags: ["TEST_DRY_RUN"]
}


SELECT 1 AS A
UNION ALL
SELECT 1 AS B
```

To recreate this error for view/assertion type, the type can be replaced by either of the two

2. Run  
   ```bash
   dataform run --dry-run --tags="TEST_DRY_RUN"
   ```

dataform version: `3.0.2` and also tested by running it from source

### PR DESCRIPTION
**Pull request by mkamysz**
Fixes #1805, as former fix in #1806 has been reverted in #1834.

* Only attempt to set metadata for tables if BigQuery option dryRun is false
* Assertions consist of two separate queries, first creating a view and second selecting from the view, expecting an empty result set; the second part of this process needs to be skipped for dry runs, as the view does not actually get created

### CODE REVIEW

File: cli/api/dbadapters/bigquery.ts [hunk 1]
```diff
@@ -330,72 +330,79 @@ export class BigQueryDbAdapter implements IDbAdapter {
...
-            }
-            onCancel?.(() => {
-              resultStream.end();
-              reject(new Error("Query cancelled."));
+          if (dryRun && query.includes('-- @dry-run:skip-results-check')) {
+            // If the above evaluated to true, this means we would be running the row count query of an assertion (see execution_sql.ts).
+            // This must be stopped during a dry run, as the view is not actually created. Therefore we skip the creation of a query job
+            // and instead directly return.
+            return { rows: [], metadata: {} };
+          } else {
```
Comment (Ekrekr) [inline cli/api/dbadapters/bigquery.ts:338]: This else can be skipped, because the function will already have been returned from the if. Also this will get rid of the indentation that is making reviewing a bit confusing.

File: cli/api/dbadapters/bigquery.ts [hunk 2]
```diff
@@ -330,72 +330,79 @@ export class BigQueryDbAdapter implements IDbAdapter {
...
-          return new Promise<IExecutionResult>((resolve, reject) => {
-            if (isCancelled) {
-              resultStream.end();
-              reject(new Error("Query cancelled."));
-              return;
-            }
-            onCancel?.(() => {
-              resultStream.end();
-              reject(new Error("Query cancelled."));
+          if (dryRun && query.includes('-- @dry-run:skip-results-check')) {
```
Comment (Ekrekr) [inline cli/api/dbadapters/bigquery.ts:333]: I'm not a fan of making this depend on the SQL contents, because we have parameters that can be passed around instead - also this won't be backwards compatible with older core versions.

I think if you look upstream, we should just be able to skip the second statement of assertions here https://github.com/dataform-co/dataform/blob/6f13b4a283805928e0233004b50e8a074c90cd33/cli/api/commands/run.ts#L416 or one level higher up. This way inserting to the SQL during compilation won't be needed

**Comment by Ceridan** [comment]
@mkamysz friendly ping, and thank you for the patch!

**Comment by mkamysz** [comment]
Hey @Ekrekr @Ceridan, thanks for reviewing and giving pointers! Should be clearer now

**Review by Ekrekr — APPROVED** [review]
Nice! Very clean now

**Comment by Ceridan** [comment]
@mkamysz, could you please merge the latest `main` branch to your branch? I believe it should fix presubmit test failures.

**Comment by mkamysz** [comment]
@Ceridan done, don't think it fixed the test failure though, did it?

**Review by Ceridan — APPROVED** [review]
